add active record queries instrumentation
platanus/prometheus_exporter pull request #1
Opened 2018-11-30 16:09 UTC by blackjid

2018-11-30 16:21 UTC, iobaixas commented on lib/prometheus_exporter/server/active_record_collector.rb
> +        PrometheusExporter::Metric::Counter.new(
@blackjid estas lineas tienen un estilo raro, yo lo hubiera escrito así:

```
@active_record_queries_duration_milliseconds = PrometheusExporter::Metric::Counter.new(
  "active_record_queries_duration_milliseconds", "Total time spent in queries."
)
```

2018-11-30 16:21 UTC, iobaixas commented on lib/prometheus_exporter/utils/rails.rb
> +        return @database_engine if @database_engine
esto también lo escribiría de otra manera:

```
def database_engine
  @database_engine ||= begin
    next :postgres unless defined?(ActiveRecord::Base)
    
    case raw_database_adapter&.to_s
    when 'postgres'   then :postgres
    when 'postgresql' then :postgres
    when 'postgis'    then :postgres
    when 'sqlite3'    then :sqlite
    when 'sqlite'     then :sqlite
    when 'mysql'      then :mysql
    when 'mysql2'     then :mysql
    else :postgres
    end
  end
end
```

2018-11-30 17:03 UTC, iobaixas requested changes

2018-11-30 17:03 UTC, iobaixas commented on lib/prometheus_exporter/instrumentation/active_record.rb
> +require 'prometheus_exporter/utils/sql_sanitizer'
según lo que hablamos, dejaría esto adentro de `start`

2018-11-30 17:03 UTC, iobaixas commented on test/server/collector_test.rb
> +    p result
este `p` se coló?

2018-11-30 17:41 UTC, blackjid commented on lib/prometheus_exporter/utils/rails.rb
> +        return @database_engine if @database_engine
ese next no debiera ser un return??

2018-11-30 17:41 UTC, blackjid commented on test/server/collector_test.rb
> +    p result
yes

2018-11-30 17:45 UTC, iobaixas commented on lib/prometheus_exporter/utils/rails.rb
> +        return @database_engine if @database_engine
no, porque está adentro de un `begin`

2018-11-30 19:49 UTC, iobaixas approved these changes

2018-12-02 23:59 UTC, lcasassa approved these changes

2019-07-17 21:27 UTC, closed without merging